/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package index;

/**
 *
 * @author delamora
 */
public class Descargas extends javax.swing.JFrame {

    /**
     * Creates new form Descargas
     */
    public Descargas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFormatoISAK = new javax.swing.JButton();
        btnClasificacionSomatotipo = new javax.swing.JButton();
        btnNomograma = new javax.swing.JButton();
        btnProforma = new javax.swing.JButton();
        btnSomatograma = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descargas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 29, 200, 40));

        btnFormatoISAK.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnFormatoISAK.setText("Proforma de anotación");
        btnFormatoISAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatoISAKActionPerformed(evt);
            }
        });
        getContentPane().add(btnFormatoISAK, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 99, 197, 40));

        btnClasificacionSomatotipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClasificacionSomatotipo.setText("Clasificación de Somatotipo");
        btnClasificacionSomatotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasificacionSomatotipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnClasificacionSomatotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 173, -1, 40));

        btnNomograma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNomograma.setText("Nomograma");
        btnNomograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomogramaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNomograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 246, 197, 40));

        btnProforma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProforma.setText("Proforma");
        btnProforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProformaActionPerformed(evt);
            }
        });
        getContentPane().add(btnProforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 127, 200, 40));

        btnSomatograma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSomatograma.setText("Somatograma");
        btnSomatograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomatogramaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomatograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 215, 200, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo1 6x4.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProformaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\downloads\\proforma.pdf");
        } catch (Exception e){}
    }//GEN-LAST:event_btnProformaActionPerformed

    private void btnFormatoISAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatoISAKActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\downloads\\Formato ISAK.xls");
        } catch (Exception e){}
    }//GEN-LAST:event_btnFormatoISAKActionPerformed

    private void btnClasificacionSomatotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasificacionSomatotipoActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\downloads\\clasificacion de somatotipo en somatocarta.pdf");
        } catch (Exception e){}
    }//GEN-LAST:event_btnClasificacionSomatotipoActionPerformed

    private void btnNomogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomogramaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\downloads\\nomograma.pdf");
        } catch (Exception e){}
    }//GEN-LAST:event_btnNomogramaActionPerformed

    private void btnSomatogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomatogramaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\downloads\\somatograma.pdf");
        } catch (Exception e){}
    }//GEN-LAST:event_btnSomatogramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Descargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Descargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Descargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Descargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Descargas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClasificacionSomatotipo;
    private javax.swing.JButton btnFormatoISAK;
    private javax.swing.JButton btnNomograma;
    private javax.swing.JButton btnProforma;
    private javax.swing.JButton btnSomatograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
