/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package index;

/**
 *
 * @author delamora
 */
public class Formulas extends javax.swing.JFrame {

    /**
     * Creates new form Formulas
     */
    public Formulas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnICC = new javax.swing.JButton();
        btnFormulaDC = new javax.swing.JButton();
        btnFormulaGC = new javax.swing.JButton();
        btnSomatotipo = new javax.swing.JButton();
        btnComposicion = new javax.swing.JButton();
        btnSomatograma = new javax.swing.JButton();
        btnValoresIMC = new javax.swing.JButton();
        btnComplexion = new javax.swing.JButton();
        btnClasificacionSomatotipos = new javax.swing.JButton();
        btnPorcentajeGrasas = new javax.swing.JButton();
        btnEscalaClasificacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fórmulas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 11, 200, 40));

        btnICC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnICC.setText("Indice Cintura Cadera");
        btnICC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnICCActionPerformed(evt);
            }
        });
        getContentPane().add(btnICC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 32));

        btnFormulaDC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnFormulaDC.setText("Fórmulas de DC");
        btnFormulaDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormulaDCActionPerformed(evt);
            }
        });
        getContentPane().add(btnFormulaDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 32));

        btnFormulaGC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnFormulaGC.setText("Fórmula %GC");
        btnFormulaGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormulaGCActionPerformed(evt);
            }
        });
        getContentPane().add(btnFormulaGC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 200, 32));

        btnSomatotipo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSomatotipo.setText("Somatotipo");
        btnSomatotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomatotipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomatotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 32));

        btnComposicion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnComposicion.setText("Composición corporal");
        btnComposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComposicionActionPerformed(evt);
            }
        });
        getContentPane().add(btnComposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 200, 32));

        btnSomatograma.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSomatograma.setText("Somatograma");
        btnSomatograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomatogramaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomatograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 200, 32));

        btnValoresIMC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnValoresIMC.setText("Valores del IMC");
        btnValoresIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValoresIMCActionPerformed(evt);
            }
        });
        getContentPane().add(btnValoresIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 32));

        btnComplexion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnComplexion.setText("Complexión");
        btnComplexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplexionActionPerformed(evt);
            }
        });
        getContentPane().add(btnComplexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 200, 32));

        btnClasificacionSomatotipos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnClasificacionSomatotipos.setText("Clasificación de somatotipos");
        btnClasificacionSomatotipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasificacionSomatotiposActionPerformed(evt);
            }
        });
        getContentPane().add(btnClasificacionSomatotipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 200, 32));

        btnPorcentajeGrasas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnPorcentajeGrasas.setText("Porcentaje ideal de grasas");
        btnPorcentajeGrasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeGrasasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPorcentajeGrasas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 200, 32));

        btnEscalaClasificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEscalaClasificacion.setText("Escala de Clasificación");
        btnEscalaClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscalaClasificacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnEscalaClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo2 7x4.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 394));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnICCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnICCActionPerformed
        FormulaICC ventana = new FormulaICC();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnICCActionPerformed

    private void btnFormulaDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormulaDCActionPerformed
        FormulaDC3 ventana = new FormulaDC3();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnFormulaDCActionPerformed

    private void btnFormulaGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormulaGCActionPerformed
        FormulaGC4 ventana = new FormulaGC4();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnFormulaGCActionPerformed

    private void btnSomatotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomatotipoActionPerformed
        FormulaSomatotipo ventana = new FormulaSomatotipo();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnSomatotipoActionPerformed

    private void btnComposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComposicionActionPerformed
        FormulaComposicion ventana = new FormulaComposicion();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnComposicionActionPerformed

    private void btnSomatogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomatogramaActionPerformed
        FormulaSomatograma ventana = new FormulaSomatograma();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnSomatogramaActionPerformed

    private void btnValoresIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValoresIMCActionPerformed
        FormulaIMC ventana = new FormulaIMC();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnValoresIMCActionPerformed

    private void btnComplexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplexionActionPerformed
        FormulaComplexion ventana = new FormulaComplexion();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnComplexionActionPerformed

    private void btnPorcentajeGrasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeGrasasActionPerformed
        FormulaPorcentajeIdeal ventana = new FormulaPorcentajeIdeal();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnPorcentajeGrasasActionPerformed

    private void btnClasificacionSomatotiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasificacionSomatotiposActionPerformed
        FormulaClasificacionSomatotipo ventana = new FormulaClasificacionSomatotipo();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnClasificacionSomatotiposActionPerformed

    private void btnEscalaClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscalaClasificacionActionPerformed
        FormulaEscalaSomatotipo ventana = new FormulaEscalaSomatotipo();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnEscalaClasificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClasificacionSomatotipos;
    private javax.swing.JButton btnComplexion;
    private javax.swing.JButton btnComposicion;
    private javax.swing.JButton btnEscalaClasificacion;
    private javax.swing.JButton btnFormulaDC;
    private javax.swing.JButton btnFormulaGC;
    private javax.swing.JButton btnICC;
    private javax.swing.JButton btnPorcentajeGrasas;
    private javax.swing.JButton btnSomatograma;
    private javax.swing.JButton btnSomatotipo;
    private javax.swing.JButton btnValoresIMC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
