package index;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import poi.ExportToWord;
import poi.Paciente;

/**
 * @author delamora
 */
public class Laboratorio extends javax.swing.JFrame {

    /**
     * Creates new form Laboratorio
     */
    public Laboratorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tpDatosPersonales = new javax.swing.JTabbedPane();
        panelDatosPersonales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbActividadFisica = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtEstatura = new javax.swing.JTextField();
        cbMasculino = new javax.swing.JCheckBox();
        cbFemenino = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTriceps = new javax.swing.JTextField();
        txtSubescapular = new javax.swing.JTextField();
        txtBiceps = new javax.swing.JTextField();
        txtPectoral = new javax.swing.JTextField();
        txtAxilar = new javax.swing.JTextField();
        txtCrestaIliaca = new javax.swing.JTextField();
        txtSupraespinal = new javax.swing.JTextField();
        txtAbdominal = new javax.swing.JTextField();
        txtMusloFrontal = new javax.swing.JTextField();
        txtPantorrillaMedial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtBrazoRelajado = new javax.swing.JTextField();
        txtBrazoContraido = new javax.swing.JTextField();
        txtCintura = new javax.swing.JTextField();
        txtAbdomen = new javax.swing.JTextField();
        txtCadera = new javax.swing.JTextField();
        txtPantorrilla = new javax.swing.JTextField();
        txtHumero = new javax.swing.JTextField();
        txtEstiloideo = new javax.swing.JTextField();
        txtFemur = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        panelMediciones = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtIMC = new javax.swing.JTextField();
        txtCC = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtEndomorfia = new javax.swing.JTextField();
        txtMesomorfia = new javax.swing.JTextField();
        txtEctomorfia = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtClasificacion = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtEndomorfiaRCD = new javax.swing.JTextField();
        txtMesomorfiaRCD = new javax.swing.JTextField();
        txtEctomorfiaRCD = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        btnDurninWomersley = new javax.swing.JToggleButton();
        btnThorlandJohnson = new javax.swing.JToggleButton();
        btnSloanBurtBlyth = new javax.swing.JToggleButton();
        btnSloan = new javax.swing.JToggleButton();
        btnPolloclkLaughridge = new javax.swing.JToggleButton();
        btnKatchMcArdle = new javax.swing.JToggleButton();
        btnLewisHaskell = new javax.swing.JToggleButton();
        btnJacksonPollock = new javax.swing.JToggleButton();
        btnJacksonAndPollock = new javax.swing.JToggleButton();
        btnWilmoreBehnke = new javax.swing.JToggleButton();
        btnWithersCraig = new javax.swing.JToggleButton();
        jLabel41 = new javax.swing.JLabel();
        txtComplexion = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtICC = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        panelComposicionCorporal = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtMasaMagra = new javax.swing.JTextField();
        txtKgGrasa = new javax.swing.JTextField();
        txtKgMusculo = new javax.swing.JTextField();
        txtKgOseo = new javax.swing.JTextField();
        txtKgResidual = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtPorcentajeGrasaReal = new javax.swing.JTextField();
        txtPorcentajeMusculoReal = new javax.swing.JTextField();
        txtPorcentajeOseoReal = new javax.swing.JTextField();
        txtPorcentajeResidualReal = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txtPorcentajeGrasaRCD = new javax.swing.JTextField();
        txtPorcentajeMusculoRCD = new javax.swing.JTextField();
        txtPorcentajeOseoRCD = new javax.swing.JTextField();
        txtPorcentajeResidualRCD = new javax.swing.JTextField();
        btnExportarWord = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1220, 600));
        setResizable(false);

        tpDatosPersonales.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        tpDatosPersonales.setMaximumSize(new java.awt.Dimension(1200, 600));
        tpDatosPersonales.setPreferredSize(new java.awt.Dimension(1200, 600));

        panelDatosPersonales.setMaximumSize(new java.awt.Dimension(1400, 600));
        panelDatosPersonales.setPreferredSize(new java.awt.Dimension(1400, 630));
        panelDatosPersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos Personales");
        panelDatosPersonales.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1195, 24));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Nombre");
        panelDatosPersonales.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 150, 23));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        panelDatosPersonales.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 858, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Actividad Física");
        panelDatosPersonales.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 36, 250, 24));

        cmbActividadFisica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbActividadFisica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Ballet", "Besibol o Softbol", "Basquetbol", "Fisicocontructivismo", "Ciclismo", "Gimnasia", "Futbol", "Natación", "Tenis", "Velocidad", "Medio fondo", "Fondo", "Triatlón", "Voleibol", "Lucha" }));
        panelDatosPersonales.add(cmbActividadFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 66, 298, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Edad");
        panelDatosPersonales.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Peso");
        panelDatosPersonales.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 120, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estatura en cm.");
        panelDatosPersonales.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Género");
        panelDatosPersonales.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 100, 298, -1));

        txtEdad.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEdadKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 120, -1));

        txtPeso.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesoKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 125, 120, -1));

        txtEstatura.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtEstatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelDatosPersonales.add(txtEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 125, 120, -1));

        cbMasculino.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbMasculino.setLabel("Masculino");
        cbMasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMasculinoMouseClicked(evt);
            }
        });
        panelDatosPersonales.add(cbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 125, -1, 25));

        cbFemenino.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbFemenino.setLabel("Femenino");
        cbFemenino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFemeninoMouseClicked(evt);
            }
        });
        panelDatosPersonales.add(cbFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(1046, 125, -1, 25));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pliegues cutáneos");
        panelDatosPersonales.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 500, 23));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Circunferencias corporales en cm.");
        panelDatosPersonales.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 156, 380, 23));

        txtTriceps.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtTriceps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTriceps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTricepsKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtTriceps, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 185, 100, -1));

        txtSubescapular.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtSubescapular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubescapular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubescapularKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtSubescapular, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 216, 100, -1));

        txtBiceps.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtBiceps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBiceps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBicepsKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtBiceps, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 247, 100, -1));

        txtPectoral.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPectoral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPectoral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPectoralKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtPectoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 278, 100, -1));

        txtAxilar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtAxilar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAxilar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAxilarKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtAxilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 309, 100, -1));

        txtCrestaIliaca.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCrestaIliaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCrestaIliaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCrestaIliacaKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtCrestaIliaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 100, -1));

        txtSupraespinal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtSupraespinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSupraespinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupraespinalKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtSupraespinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 371, 100, -1));

        txtAbdominal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtAbdominal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAbdominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAbdominalKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtAbdominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 402, 100, -1));

        txtMusloFrontal.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtMusloFrontal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMusloFrontal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMusloFrontalKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtMusloFrontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 433, 100, -1));

        txtPantorrillaMedial.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPantorrillaMedial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPantorrillaMedial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPantorrillaMedialKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtPantorrillaMedial, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 464, 100, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setText("Tríceps");
        panelDatosPersonales.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, 180, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Subescapular");
        panelDatosPersonales.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 216, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Bíceps");
        panelDatosPersonales.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 247, 96, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("Pectoral");
        panelDatosPersonales.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 278, 96, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Axilar");
        panelDatosPersonales.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 309, 96, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setText("Cresta iliaca");
        panelDatosPersonales.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 96, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setText("Supraespinal");
        panelDatosPersonales.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 371, 96, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setText("Abdominal");
        panelDatosPersonales.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 405, 180, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Muslo Frontal");
        panelDatosPersonales.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 433, 180, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setText("Pantorrilla medial");
        panelDatosPersonales.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 464, 180, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("Brazo relajado");
        panelDatosPersonales.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 185, 180, 25));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setText("Brazo contraido");
        panelDatosPersonales.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 216, 180, 25));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setText("Cintura");
        panelDatosPersonales.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 247, 180, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setText("Abdomen");
        panelDatosPersonales.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 278, 180, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel24.setText("Cadera");
        panelDatosPersonales.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 309, 180, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setText("Pantorrilla");
        panelDatosPersonales.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 180, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Diámetros oseos");
        panelDatosPersonales.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 371, 380, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel27.setText("Húmero");
        panelDatosPersonales.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 402, 180, 23));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel28.setText("Estiloideo");
        panelDatosPersonales.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 433, 180, 27));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel29.setText("Fémur");
        panelDatosPersonales.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 466, 180, -1));

        txtBrazoRelajado.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtBrazoRelajado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBrazoRelajado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrazoRelajadoKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtBrazoRelajado, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 185, 100, -1));

        txtBrazoContraido.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtBrazoContraido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBrazoContraido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrazoContraidoKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtBrazoContraido, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 216, 100, -1));

        txtCintura.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCintura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCintura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCinturaKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 247, 100, -1));

        txtAbdomen.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtAbdomen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAbdomen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAbdomenKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtAbdomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 278, 100, -1));

        txtCadera.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCadera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCadera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCaderaKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtCadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 309, 100, -1));

        txtPantorrilla.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtPantorrilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPantorrilla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPantorrillaKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtPantorrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 100, -1));

        txtHumero.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtHumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHumeroKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtHumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 402, 100, -1));

        txtEstiloideo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtEstiloideo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstiloideo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstiloideoKeyReleased(evt);
            }
        });
        panelDatosPersonales.add(txtEstiloideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 433, 100, -1));

        txtFemur.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtFemur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelDatosPersonales.add(txtFemur, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 464, 100, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3 14x6.jpg"))); // NOI18N
        panelDatosPersonales.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 570));

        tpDatosPersonales.addTab("Datos Personales", panelDatosPersonales);

        panelMediciones.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelMedicionesComponentShown(evt);
            }
        });
        panelMediciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Índices");
        panelMediciones.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1175, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("IMC");
        panelMediciones.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 47, 100, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("CC cm");
        panelMediciones.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 47, 100, -1));

        txtIMC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtIMC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMCActionPerformed(evt);
            }
        });
        panelMediciones.add(txtIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 70, 100, 30));

        txtCC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCActionPerformed(evt);
            }
        });
        panelMediciones.add(txtCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 70, 100, -1));

        jLabel34.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Somatotipo");
        panelMediciones.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 1175, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Endomorfia");
        panelMediciones.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 140, -1, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Mesomorfia");
        panelMediciones.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 140, -1, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Ectomorfia");
        panelMediciones.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 140, 80, 30));

        txtEndomorfia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEndomorfia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEndomorfia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndomorfiaActionPerformed(evt);
            }
        });
        panelMediciones.add(txtEndomorfia, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 176, 80, 30));

        txtMesomorfia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMesomorfia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMesomorfia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesomorfiaActionPerformed(evt);
            }
        });
        panelMediciones.add(txtMesomorfia, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 176, 80, 30));

        txtEctomorfia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEctomorfia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEctomorfia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEctomorfiaActionPerformed(evt);
            }
        });
        panelMediciones.add(txtEctomorfia, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 176, 80, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Clasificación");
        panelMediciones.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 140, 200, 40));

        txtClasificacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtClasificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClasificacionActionPerformed(evt);
            }
        });
        panelMediciones.add(txtClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 186, 200, 40));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Recomendado");
        panelMediciones.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 206, 180, 33));

        txtEndomorfiaRCD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEndomorfiaRCD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelMediciones.add(txtEndomorfiaRCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 245, 80, 30));

        txtMesomorfiaRCD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMesomorfiaRCD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelMediciones.add(txtMesomorfiaRCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 245, 80, 30));

        txtEctomorfiaRCD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEctomorfiaRCD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelMediciones.add(txtEctomorfiaRCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 245, 80, 30));

        jLabel40.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Fórmulas para determinar DC y %GC");
        panelMediciones.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, 1175, -1));

        btnDurninWomersley.setText("Durnin y Womersley (1974)");
        btnDurninWomersley.setToolTipText("Varones \nEdad: 17 - 72 \nCaracterística: variedad de tipos corporales \nMujeres Edad: 16 - 68");
        panelMediciones.add(btnDurninWomersley, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 305, 30));

        btnThorlandJohnson.setText("Thorland, Johnson, Tharp, Housh y Cisar (1984)");
        btnThorlandJohnson.setToolTipText("Varones \nEdad: Media 17.43 \nCaracterística: Deportistas nivel nacional \nMujeres \nEdad: Media 16.51");
        panelMediciones.add(btnThorlandJohnson, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 436, 305, 30));

        btnSloanBurtBlyth.setText("Sloan, Burt y Blyth (1962)");
        btnSloanBurtBlyth.setToolTipText("Mujeres \nEdad: 17 – 25 \nCaracterísticas: Estudiantes universitarios");
        panelMediciones.add(btnSloanBurtBlyth, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 472, 305, 30));

        btnSloan.setText("Sloan (1967)");
        btnSloan.setToolTipText("Varones \nEdad: 18 – 26 \nCaracterística: Estudiantes universitarios");
        panelMediciones.add(btnSloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 508, 305, 31));

        btnPolloclkLaughridge.setText("Pollock, Laughridge, Coleman, Linneurd y Jackson (1975)");
        btnPolloclkLaughridge.setToolTipText("Mujeres\nEdad: 18 – 22 \nCaracterísticas: estudiantes universitarios de educación física");
        panelMediciones.add(btnPolloclkLaughridge, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 508, -1, 31));

        btnKatchMcArdle.setText("Katch y McArdle (1973)");
        btnKatchMcArdle.setToolTipText("Varones \nEdad: media 19.3 \nCaracterísticas: estudiantes universitarios de educación física");
        panelMediciones.add(btnKatchMcArdle, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 472, 305, 30));

        btnLewisHaskell.setText("Lewis, Haskell, Perry, Kovacevic y Wood (1978)");
        btnLewisHaskell.setToolTipText("Mujeres \nEdad: 30-59 \nCaracterísticas: corredoras de media y larga distancia y nadadores nacionales e internacionales");
        panelMediciones.add(btnLewisHaskell, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 436, 305, 30));

        btnJacksonPollock.setText("Jackson, Pollock y y Ward (1980)");
        btnJacksonPollock.setToolTipText("Mujeres \nEdad: 18-55 \nCaracterísticas: amplio rango estructura corporal variable");
        panelMediciones.add(btnJacksonPollock, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 400, 305, 30));

        btnJacksonAndPollock.setText("Jackson y Pollock... (1978)");
        btnJacksonAndPollock.setToolTipText("Varones y Mujeres\nCaracterísticas: Atletas");
        panelMediciones.add(btnJacksonAndPollock, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 489, 305, 30));

        btnWilmoreBehnke.setText("Wilmore y Behnke (1969)");
        btnWilmoreBehnke.setToolTipText("Varones \nEdad: 16.80 – 36.80 \nCaracterísticas: estudiantes universitarios de educación física \n\nMujeres \nEdad: 17.80 +/- 47.80");
        panelMediciones.add(btnWilmoreBehnke, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 419, 305, 30));

        btnWithersCraig.setText("Withers, Craig, Bourdon, y Norton (1987)");
        btnWithersCraig.setToolTipText("Varones \nEdad: 25.4- 39.1 \nCaracterísticas: nivel internacional y nacional en diferentes disciplinas deportivas\n\nMujeres \nEdad 11.2 – 41.4");
        panelMediciones.add(btnWithersCraig, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 455, 305, 30));

        jLabel41.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Complexión");
        panelMediciones.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 281, 230, 40));

        txtComplexion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtComplexion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComplexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplexionActionPerformed(evt);
            }
        });
        panelMediciones.add(txtComplexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 327, 230, 33));

        jLabel42.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("ICC");
        panelMediciones.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 281, 230, 40));

        txtICC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtICC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtICC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtICCActionPerformed(evt);
            }
        });
        panelMediciones.add(txtICC, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 327, 230, 33));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3 14x6.jpg"))); // NOI18N
        panelMediciones.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 570));

        tpDatosPersonales.addTab("Mediciones", panelMediciones);

        panelComposicionCorporal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelComposicionCorporalComponentShown(evt);
            }
        });
        panelComposicionCorporal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Composición corporal");
        panelComposicionCorporal.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, 1175, 35));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Kg. Masa magra");
        panelComposicionCorporal.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 200, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel45.setText("Kg. Grasa");
        panelComposicionCorporal.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 100, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel46.setText("Kg. Músculo");
        panelComposicionCorporal.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 100, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel47.setText("Kg. Óseo");
        panelComposicionCorporal.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 100, 30));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel48.setText("Kg. Residual");
        panelComposicionCorporal.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 100, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("REAL");
        panelComposicionCorporal.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 170, 35));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("RECOMENDADO");
        panelComposicionCorporal.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 250, 35));

        txtMasaMagra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtMasaMagra, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 120, 30));

        txtKgGrasa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtKgGrasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 100, 30));

        txtKgMusculo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtKgMusculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 100, 30));

        txtKgOseo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtKgOseo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 100, 30));

        txtKgResidual.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtKgResidual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 100, 30));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setText("% Grasa");
        panelComposicionCorporal.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 80, 30));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setText("% Músculo");
        panelComposicionCorporal.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 80, 30));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("% Óseo");
        panelComposicionCorporal.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 80, 30));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setText("% Residual");
        panelComposicionCorporal.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 80, 30));

        txtPorcentajeGrasaReal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtPorcentajeGrasaReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 100, 30));

        txtPorcentajeMusculoReal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtPorcentajeMusculoReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 100, 30));

        txtPorcentajeOseoReal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtPorcentajeOseoReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 100, 30));

        txtPorcentajeResidualReal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtPorcentajeResidualReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 100, 30));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel55.setText("% Grasa");
        panelComposicionCorporal.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 100, 30));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel56.setText("% Músculo");
        panelComposicionCorporal.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 100, 30));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel57.setText("% Óseo");
        panelComposicionCorporal.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 100, 30));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel58.setText("% Residual");
        panelComposicionCorporal.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 100, 30));

        txtPorcentajeGrasaRCD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtPorcentajeGrasaRCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 100, -1));

        txtPorcentajeMusculoRCD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtPorcentajeMusculoRCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 100, 30));

        txtPorcentajeOseoRCD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtPorcentajeOseoRCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 100, 30));

        txtPorcentajeResidualRCD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelComposicionCorporal.add(txtPorcentajeResidualRCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 100, 30));

        btnExportarWord.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnExportarWord.setLabel("Exportar a Word");
        btnExportarWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarWordActionPerformed(evt);
            }
        });
        panelComposicionCorporal.add(btnExportarWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, 150, 40));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3 14x6.jpg"))); // NOI18N
        panelComposicionCorporal.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 570));

        tpDatosPersonales.addTab("Composición corporal", panelComposicionCorporal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1216, 641);
    }// </editor-fold>//GEN-END:initComponents
    
    private void panelMedicionesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelMedicionesComponentShown
        if(txtNombre.getText().isEmpty() || txtEdad.getText().isEmpty() || txtPeso.getText().isEmpty() || txtEstatura.getText().isEmpty() ||  
                !(cbMasculino.isSelected() || cbFemenino.isSelected()) ||
                txtTriceps.getText().isEmpty() || 
                txtSubescapular.getText().isEmpty() || 
                txtBiceps.getText().isEmpty() ||
                txtPectoral.getText().isEmpty() ||
                txtAxilar.getText().isEmpty() ||
                txtCrestaIliaca.getText().isEmpty() ||  
                txtSupraespinal.getText().isEmpty() ||
                txtAbdominal.getText().isEmpty() ||
                txtMusloFrontal.getText().isEmpty() ||
                txtPantorrillaMedial.getText().isEmpty() ||
                
                txtBrazoRelajado.getText().isEmpty() ||
                txtBrazoContraido.getText().isEmpty() || 
                txtCintura.getText().isEmpty() || 
                txtAbdomen.getText().isEmpty() ||
                txtCadera.getText().isEmpty() ||
                txtPantorrilla.getText().isEmpty() || 
                txtHumero.getText().isEmpty() || 
                txtEstiloideo.getText().isEmpty() ||
                txtFemur.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Necesita introducir todos los datos en la pestaña de \"Datos Personales\"");
        } else {
            txtIMCActionPerformed(null);
            txtCCActionPerformed(null);
            txtEndomorfiaActionPerformed(null);
            txtMesomorfiaActionPerformed(null);
            txtEctomorfiaActionPerformed(null);
            txtClasificacionActionPerformed(null);
            txtICCActionPerformed(null);
            txtComplexionActionPerformed(null);
        }
    }//GEN-LAST:event_panelMedicionesComponentShown
	
    private void txtIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMCActionPerformed
        double peso = 0;
        double estatura = 0;
        
        txtIMC.setEditable(false);
        
        try{
            peso = Double.parseDouble(txtPeso.getText());
            estatura = Double.parseDouble(txtEstatura.getText());
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "El dato: " + nfe.getMessage().substring(18) + " NO es un dato válido");
        }
        if(peso > 0 && estatura > 0){
            DecimalFormat df = new DecimalFormat("#.##");
            txtIMC.setText(String.valueOf(df.format(peso/(Math.pow((estatura/100), 2)))));
        } else{
            JOptionPane.showMessageDialog(rootPane, "El peso y la estatura deben ser mayores a cero");
        }
    }//GEN-LAST:event_txtIMCActionPerformed
	
    private void txtCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCActionPerformed
        double cintura = 0;
        double cadera = 0;
        
        txtCC.setEditable(false);
        
        try{
        cadera = Double.parseDouble(txtCadera.getText());
        cintura = Double.parseDouble(txtCintura.getText());
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "El dato: " + nfe.getMessage().substring(18) + " NO es un dato válido");
        }
        if (cadera > 0 && cintura > 0){
            DecimalFormat df = new DecimalFormat("#.##");
            txtCC.setText(String.valueOf(df.format(cintura/cadera)));
        } else {
            JOptionPane.showMessageDialog(rootPane, "EL diámetro de la cadera y la cintura deben ser mayores a cero");
        }
    }//GEN-LAST:event_txtCCActionPerformed

    private void txtEndomorfiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndomorfiaActionPerformed
        double triceps = 0;
        double subescapular = 0;
        double supraespinal = 0;
        double estatura = 0;
        double endomorfiaCorregida = 0;
        
        txtEndomorfia.setEditable(false);
       
        try{
            triceps = Double.parseDouble(txtTriceps.getText());
            subescapular = Double.parseDouble(txtSubescapular.getText());
            supraespinal = Double.parseDouble(txtSupraespinal.getText());
            estatura = Double.parseDouble(txtEstatura.getText());
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "El dato: " + nfe.getMessage().substring(18) + " NO es un dato válido");
        }
        if(triceps > 0 && subescapular > 0 && supraespinal > 0 && estatura > 0){
            endomorfiaCorregida = (triceps + subescapular + supraespinal)*(170.18 / estatura);
            DecimalFormat df = new DecimalFormat("#.#");
            txtEndomorfia.setText(String.valueOf(df.format(-0.7182 + 0.1451 * endomorfiaCorregida - 0.00068 * 
                    (Math.pow(endomorfiaCorregida, 2)) + 0.0000014 * (Math.pow(endomorfiaCorregida, 3)))));
        } else {
            if(supraespinal == 0 ){
                JOptionPane.showMessageDialog(rootPane, "EL diámetro Supraespinal debe ser mayor a cero: ");
            }
        }
    }//GEN-LAST:event_txtEndomorfiaActionPerformed

    private void txtMesomorfiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesomorfiaActionPerformed
        double brazoCorregido = 0;
        double brazoContraido = 0;
        double triceps = 0;
        double pantorrillaCorregida = 0;
        double pantorrilla = 0;
        double pantorrillaMedial = 0;
        double humero = 0;
        double femur = 0;
        double estatura = 0;
        
        txtMesomorfia.setEditable(false);
        
        try{
            brazoContraido = Double.parseDouble(txtBrazoContraido.getText());
            triceps = Double.parseDouble(txtTriceps.getText());
            pantorrilla = Double.parseDouble(txtPantorrilla.getText());
            pantorrillaMedial = Double.parseDouble(txtPantorrillaMedial.getText());
            humero = Double.parseDouble(txtHumero.getText());
            femur = Double.parseDouble(txtFemur.getText());
            estatura = Double.parseDouble(txtEstatura.getText());
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "El dato: " + nfe.getMessage().substring(18) + " NO es un dato válido");
        }
        if(brazoContraido > 0 && triceps > 0 && pantorrilla > 0 && pantorrillaMedial > 0 && humero > 0 && femur > 0 && estatura > 0){
            brazoCorregido = brazoContraido - triceps/10;
            pantorrillaCorregida = pantorrilla - pantorrillaMedial/10;
            DecimalFormat df = new DecimalFormat("#.#");
            txtMesomorfia.setText(String.valueOf(df.format(0.858 * humero + 0.601 * femur + 0.188 * brazoCorregido + 0.161 * 
                    pantorrillaCorregida - estatura * 0.131 + 4.5)));
        } else {
            if(brazoContraido == 0 || pantorrilla == 0 || humero == 0 || femur == 0 ){
                JOptionPane.showMessageDialog(rootPane, "EL diámetro de los siguientes parámetros deben ser mayores a cero: "
                        + "Brazo contraido, Pantorrilla, Húmero y Femur");
            }
        }
    }//GEN-LAST:event_txtMesomorfiaActionPerformed

    private void txtEctomorfiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEctomorfiaActionPerformed
        double estatura = 0;
        double peso = 0;
        double indicePonderal = 0;
        
        txtEctomorfia.setEditable(false);
        
        try{
            estatura = Double.parseDouble(txtEstatura.getText());
            peso = Double.parseDouble(txtPeso.getText());
        } catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "El dato: " + nfe.getMessage().substring(18) + " NO es un dato válido");
        }
        
        DecimalFormat df = new DecimalFormat("#.#");
        
        if(estatura > 0 && peso > 0){
            indicePonderal = estatura / Math.cbrt(peso);
            if(indicePonderal >= 40.75){
                txtEctomorfia.setText(String.valueOf(df.format((indicePonderal * 0.732) - 28.58)));
            } else if(indicePonderal < 40.75 && indicePonderal >= 38.28){
                txtEctomorfia.setText(String.valueOf(df.format((indicePonderal * 0.463) - 17.63)));
            } else {
                txtEctomorfia.setText("0.1");
            }
        }
    }//GEN-LAST:event_txtEctomorfiaActionPerformed

    private void txtClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClasificacionActionPerformed
        double endomorfia = 0;
        double mesomorfia = 0;
        double ectomorfia = 0;
        try{
            endomorfia = Double.parseDouble(txtEndomorfia.getText());
            mesomorfia = Double.parseDouble(txtMesomorfia.getText());
            ectomorfia = Double.parseDouble(txtEctomorfia.getText());
        } catch (NumberFormatException nfe){
            nfe.printStackTrace();
        }
        
        txtClasificacion.setEditable(false);
        while(true){
            if((endomorfia == mesomorfia) && (endomorfia == ectomorfia) && (mesomorfia == ectomorfia)){
                txtClasificacion.setText("Central");
                break;
            }
            if((endomorfia > mesomorfia) && (endomorfia > ectomorfia) && (((ectomorfia - mesomorfia) <= 0.599) && ((ectomorfia - mesomorfia) >= -0.599))){
                txtClasificacion.setText("Endomorfo - balanceado");
                break;
            }
            if((endomorfia > mesomorfia) && (endomorfia > ectomorfia) && (ectomorfia > mesomorfia)){
                txtClasificacion.setText("Endomorfo - ectomorfo");
                break;
            }
            if((endomorfia > mesomorfia) && (endomorfia > ectomorfia) && (mesomorfia > ectomorfia)){
                txtClasificacion.setText("Endomorfo-mesomorfo");
                break;
            }
            if((((endomorfia - mesomorfia) <= 0.599) && ((endomorfia - mesomorfia) >= -0.599)) && ((ectomorfia < mesomorfia) &&( ectomorfia < endomorfia))){
                txtClasificacion.setText("Endomorfo mesomorfo");
                break;
            }
            if((mesomorfia > endomorfia) && (mesomorfia > ectomorfia) && (((endomorfia - ectomorfia) <= 0.599) && ((endomorfia - ectomorfia) >= -0.599))){
                txtClasificacion.setText("Mesomorfo balanceado");
                break;
            }
            if((mesomorfia > endomorfia) && (mesomorfia > ectomorfia) && (endomorfia > ectomorfia)){
                txtClasificacion.setText("Mesomorfo - endomorfo");
                break;
            }
            if((mesomorfia > ectomorfia) && (mesomorfia > endomorfia) && (ectomorfia > endomorfia)){
                txtClasificacion.setText("Mesomorfo ectomorfo");
                break;
            }
            if((((ectomorfia - mesomorfia) <= 0.599) && ((ectomorfia - mesomorfia) >= -0.599)) && ((endomorfia < mesomorfia) &&( endomorfia < ectomorfia))){
                txtClasificacion.setText("Ectomorfo mesomorfo");
                break;
            }
            if((ectomorfia > endomorfia) && (ectomorfia > mesomorfia) && (((endomorfia - mesomorfia) <= 0.599) && ((endomorfia - mesomorfia) >= -0.599))){
                txtClasificacion.setText("Ectomorfo balanceado");
                break;
            }
            if((((endomorfia - ectomorfia) <= 0.599) && ((endomorfia - ectomorfia) >= -0.599)) && ((mesomorfia < ectomorfia) &&( mesomorfia < endomorfia))){
                txtClasificacion.setText("Ectomorfo endomorfo");
                break;
            }
            if((ectomorfia > endomorfia) && (ectomorfia > mesomorfia) && (mesomorfia > endomorfia)){
                txtClasificacion.setText("Ectomorfo - mesomorfo");
                break;
            }
            if((ectomorfia > endomorfia) && (ectomorfia > mesomorfia) && (endomorfia > mesomorfia)){
                txtClasificacion.setText("Ectomorfo endomorfo");
                break;
            }
        }
    }//GEN-LAST:event_txtClasificacionActionPerformed

    private void txtICCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtICCActionPerformed
        txtICC.setEditable(false);
        try{
            double cintura = Double.parseDouble(txtCintura.getText());
            double cadera = Double.parseDouble(txtCadera.getText());
            if(cadera > 0){
                Double ICC = cintura/cadera;
                if(cbMasculino.isSelected()){
                    if(ICC > 1.0){
                        txtICC.setText("Alto");
                    } else {
                        if((ICC >= 0.9)&&(ICC <= 1.0)){
                            txtICC.setText("Moderado");
                        }
                        else{
                            txtICC.setText("Bajo");
                        }
                    }
                } else {
                    if(ICC > 0.85){
                        txtICC.setText("Alto");
                    } else {
                        if((ICC >= 0.75)&&(ICC <= 0.85)){
                            txtICC.setText("Moderado");
                        }
                        else{
                            txtICC.setText("Bajo");
                        }
                    }
                }
            } else {
                txtICC.setText("Introduzca diametro cadera");
            }
        } catch (NumberFormatException nfe){
            nfe.printStackTrace();
        }
    }//GEN-LAST:event_txtICCActionPerformed

    private void panelComposicionCorporalComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelComposicionCorporalComponentShown
        double peso = 0;
        double estatura = 0;
        double edad = 0;
        double subescapular = 0;
        double crestaIliaca = 0;
        double triceps = 0;
        double biceps = 0;
        double pantorrillaMedial = 0;
        double axilar = 0;
        double abdominal = 0;
        double musloFrontal = 0;
        double brazoRelajado = 0;
        double supraespinal = 0;
        double abdomen = 0;
        double pectoral = 0;
        double estiloideo = 0;
        double femur = 0;
        String porcentajeGrasaRCD = "";
        int actividadFisica = 0;
        
        int botonesSeleccionados = 0;
        
        double dc= 0;
        double gcDW = 0;
        double gcTJ = 0;
        double gcSBB = 0;
        double gcSloan = 0;
        double gcJPW = 0;
        double gcLHPKW = 0;
        double gcKM = 0;
        double gcPLCLJ = 0;
        double gcWB = 0;
        double gcJ = 0;
        double gcWCBN = 0;
        
        txtMasaMagra.setEditable(false);
        txtKgGrasa.setEditable(false);
        txtKgMusculo.setEditable(false);
        txtKgOseo.setEditable(false);
        txtKgResidual.setEditable(false);
        
        txtPorcentajeGrasaReal.setEditable(false);
        txtPorcentajeMusculoReal.setEditable(false);
        txtPorcentajeOseoReal.setEditable(false);
        txtPorcentajeResidualReal.setEditable(false);
        
        //txtPorcentajeGrasaRCD.setEditable(false);
        
        try{
            peso = Double.parseDouble(txtPeso.getText());
            estatura = Double.parseDouble(txtEstatura.getText());
            triceps = Double.parseDouble(txtTriceps.getText());
            biceps = Double.parseDouble(txtBiceps.getText());
            subescapular = Double.parseDouble(txtSubescapular.getText());
            crestaIliaca = Double.parseDouble(txtCrestaIliaca.getText());
            axilar = Double.parseDouble(txtAxilar.getText());
            abdominal = Double.parseDouble(txtAbdominal.getText());
            musloFrontal = Double.parseDouble(txtMusloFrontal.getText());
            pantorrillaMedial =  Double.parseDouble(txtPantorrillaMedial.getText());
            edad = Double.parseDouble(txtEdad.getText());
            brazoRelajado = Double.parseDouble(txtBrazoRelajado.getText());
            pectoral = Double.parseDouble(txtPectoral.getText());
            estiloideo = Double.parseDouble(txtEstiloideo.getText());
            femur = Double.parseDouble(txtFemur.getText());
            abdomen = Double.parseDouble(txtAbdomen.getText());
            supraespinal = Double.parseDouble(txtSupraespinal.getText());
        } catch (NumberFormatException nfe){}
        
        try{
            actividadFisica = cmbActividadFisica.getSelectedIndex();
        } catch (Exception e){}
        
        /*switch (actividadFisica) {
            case 0:
                if(cbFemenino.isSelected() && (edad >= 20 && edad <= 29)) {
                    porcentajeGrasaRCD = "29-34";
                }
                if(cbMasculino.isSelected() && (edad >= 20 && edad <= 29)) {
                    porcentajeGrasaRCD = "21-26";
                }
            break;
            case 1:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "13-20";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "8-14";
                }
            break;
            case 2:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "13-20";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "8-14";
                }
            break;
            case 3:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "20-27";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "7-11";
                }
            break;
            case 4:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "9-13";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "6-9";
                }
            break;
            case 5:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "15";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "8-10";
                }
            break;
            case 6:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "10-17";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "5-10";
                }
            break;
            case 7:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "10";
                }
            break;
            case 8:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "14-24";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "9-12";
                }
            break;
            case 9:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "20";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "15-16";
                }
            break;
            case 10:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "11-19";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "8-9";
                }
            break;
            case 11:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "10-14";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "7-12";
                }
            break;
            case 12:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "10-19";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "6-13";
                }
            break;
            case 13:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "7-17";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "5-11";
                }
            break;
            case 14:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "16-25";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "11-12";
                }
            break;
            case 15:
                if(cbFemenino.isSelected()) {
                    porcentajeGrasaRCD = "";
                }
                if(cbMasculino.isSelected()) {
                    porcentajeGrasaRCD = "5-12";
                }
            break;                            
        }*/
        
        if(btnDurninWomersley.isSelected()){
            botonesSeleccionados++;
            double x1 = triceps + biceps + subescapular + crestaIliaca;
            if(cbMasculino.isSelected()){
                dc = 1.1765 - 0.0744 * (Math.log10(x1));
            } else {
                dc = 1.1567 - 0.0717 * (Math.log10(x1));
            }
            gcDW = 495 / dc - 450;//Siri
        }
        
        if(btnThorlandJohnson.isSelected()){
            botonesSeleccionados++;
            if(cbMasculino.isSelected()){
                double x1 = triceps + subescapular + axilar + crestaIliaca + abdominal + musloFrontal + pantorrillaMedial;
                dc = 1.1091 - 0.00052 * x1 + 0.00000032 * Math.pow(x1,2);
            } else {
                double x2 = triceps + subescapular + crestaIliaca;
                dc = 1.0987 - 0.00122 * x2 + 0.00000263 * Math.pow(x2,2);
            }
            gcTJ = 495 / dc - 450;//Siri
        }
        
        if(btnSloanBurtBlyth.isSelected()){
            if(cbFemenino.isSelected()){
                botonesSeleccionados++;
                dc = 1.0764 - 0.00081 * crestaIliaca - 0.00088 * triceps;
                gcSBB = 495 / dc - 450;//Siri
            }
        }
        
        if(btnSloan.isSelected()){
            if(cbMasculino.isSelected()){
                botonesSeleccionados++;
                dc = 1.1043 - 0.001327 * musloFrontal - 0.001310 * subescapular;
                gcSloan = 457 / dc - 414;
            }
        }
        
        if(btnJacksonPollock.isSelected()){
            if(cbFemenino.isSelected()){
                botonesSeleccionados++;
                double x2= triceps + musloFrontal + crestaIliaca;
                dc = 1.21389 - 0.04057 * Math.log10(x2) - 0.00016 * edad;
                gcJPW = 495 / dc - 450;//Siri
            }
        }
        
        if(btnLewisHaskell.isSelected()){
            if(cbFemenino.isSelected()){
                botonesSeleccionados++;
                dc = 0.97845 - 0.0002 * triceps + 0.00088 * estatura - 0.00122 * subescapular - 0.00234 * brazoRelajado;
                gcLHPKW = 495 / dc - 450;//Siri
            }
        }
        
        if(btnKatchMcArdle.isSelected()){
            if(cbMasculino.isSelected()){
                botonesSeleccionados++;
                dc = 1.09665 - 0.00103 * triceps - 0.00056 * subescapular - 0.00054 * abdominal;
                gcKM = 457 / dc - 414;
            }
        }
        
        if(btnPolloclkLaughridge.isSelected()){
            if(cbFemenino.isSelected()){
                botonesSeleccionados++;
                dc = 1.0852 - 0.0008 * crestaIliaca - 0.0011 * musloFrontal;
                gcPLCLJ = 495 / dc - 450;//Siri
            }
        }
        
        if(btnWilmoreBehnke.isSelected()){
            botonesSeleccionados++;
            if(cbMasculino.isSelected()){
                dc = 1.08543 - 0.000886 * abdominal - 0.00040 * musloFrontal;
            } else {
                dc = 1.06234 - 0.00068 * subescapular - 0.00039 * triceps - 0.00025 * musloFrontal;
            }
            gcWB = 495 / dc - 450;//Siri
        }
        
        if(btnWithersCraig.isSelected()){
            botonesSeleccionados++;
            if(cbMasculino.isSelected()){
                dc = 1.0988 - 0.0004 * (triceps + subescapular + biceps + supraespinal + abdominal + musloFrontal + pantorrillaMedial);
            } else {
                dc = 1.17484 - 0.07229 * Math.log10(triceps + subescapular + supraespinal + pantorrillaMedial);
            }
            gcWCBN = 495 / dc - 450;//Siri
        }
        
        if(btnJacksonAndPollock.isSelected()){
            botonesSeleccionados++;
            if(cbMasculino.isSelected()){
                dc = 1.112 - 0.00043499 * (triceps + pectoral + axilar + subescapular + abdomen + crestaIliaca + musloFrontal)
                        + 0.00000055 * Math.pow((triceps + pectoral + axilar + subescapular + abdomen + crestaIliaca + musloFrontal),2) 
                        - 0.00028826 * edad;
            } else {
                dc = 1.096095 - 0.0006952 * (triceps + supraespinal +abdomen + musloFrontal) + 0.0000011 * 
                        Math.pow((triceps + supraespinal +abdomen + musloFrontal),2) - 0.0000714 * edad;
            }
            gcJ = 495 / dc - 450;//Siri
        }
        
        double porcentajeGrasaCorporal = (gcDW + gcTJ + gcSBB + gcSloan + gcJPW + gcLHPKW + gcKM + gcPLCLJ + gcWB + gcJ + gcWCBN) / botonesSeleccionados;
        
        double kiloGrasa = (peso * porcentajeGrasaCorporal)/100;
        double masaMagra = peso - (peso * porcentajeGrasaCorporal)/100;
        double kiloOseo = 3.02 * Math.pow((Math.pow(estatura/100,2) * estiloideo/100 * femur/100 * 400),0.712);
        double porcentajeOseo = (kiloOseo * 100) / peso;
        double porcentajeResidual = 0;
        if(cbMasculino.isSelected()){
            porcentajeResidual = 24;
        } else {
            porcentajeResidual = 21;
        }
        double porcentajeMusculo = 100 - (porcentajeGrasaCorporal + porcentajeOseo + porcentajeResidual);
        double kiloMusculo = (peso * porcentajeMusculo) / 100;
        double kiloResidual = (peso * porcentajeResidual)/100;
        
        DecimalFormat df = new DecimalFormat("#.#");
        
        txtMasaMagra.setText(String.valueOf(df.format(masaMagra)));
        txtKgGrasa.setText(String.valueOf(df.format(kiloGrasa)));
        txtKgMusculo.setText(String.valueOf(df.format(kiloMusculo)));
        txtKgOseo.setText(String.valueOf(df.format(kiloOseo)));
        txtKgResidual.setText(String.valueOf(kiloResidual));
        txtPorcentajeGrasaReal.setText(String.valueOf(df.format(porcentajeGrasaCorporal)));
        txtPorcentajeMusculoReal.setText(String.valueOf(df.format(porcentajeMusculo)));
        txtPorcentajeOseoReal.setText(String.valueOf(df.format(porcentajeOseo)));
        txtPorcentajeResidualReal.setText(String.valueOf(df.format(porcentajeResidual)));
        
        //txtPorcentajeOseoRCD.setText(String.valueOf(df.format(porcentajeOseo)));
        //txtPorcentajeResidualRCD.setText(String.valueOf(df.format(porcentajeResidual)));
        
        //txtPorcentajeGrasaRCD.setText(porcentajeGrasaRCD);
        
    }//GEN-LAST:event_panelComposicionCorporalComponentShown

    private void txtComplexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplexionActionPerformed
        double humero = Double.parseDouble(txtHumero.getText());
        double edad = Double.parseDouble(txtEdad.getText());
        
        if(cbMasculino.isSelected()){
            if(edad <= 24){
                if (humero <= 6.7){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.7)&&(humero < 7.6)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if((edad >= 25)&&(edad <= 34)){
                if (humero <= 6.8){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.8)&&(humero < 7.6)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if((edad >= 35)&&(edad <= 44)){
                if (humero <= 6.7){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.7)&&(humero < 7.7)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if((edad >= 45)&&(edad <= 54)){
                if (humero <= 6.9){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.9)&&(humero < 7.9)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if((edad >= 55)&&(edad <= 64)){
                if (humero <= 6.9){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.9)&&(humero < 7.9)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if(edad >= 65){
                if (humero <= 6.9){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.8)&&(humero < 7.8)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
        } else {
            if(edad <= 24){
                if (humero <= 5.8){
                    txtComplexion.setText("Chica");
                } else if ((humero > 5.8)&&(humero < 6.6)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if((edad >= 25)&&(edad <= 34)){
                if (humero <= 5.8){
                    txtComplexion.setText("Chica");
                } else if ((humero > 5.8)&&(humero < 6.7)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if((edad >= 35)&&(edad <= 44)){
                if (humero <= 6.0){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.0)&&(humero < 7.0)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if((edad >= 45)&&(edad <= 54)){
                if (humero <= 6.0){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.0)&&(humero < 7.1)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if((edad >= 55)&&(edad <= 64)){
                if (humero <= 6.1){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.1)&&(humero < 7.2)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
            if(edad >= 65){
                if (humero <= 6.1){
                    txtComplexion.setText("Chica");
                } else if ((humero > 6.1)&&(humero < 7.0)){
                    txtComplexion.setText("Mediana");
                } else {
                    txtComplexion.setText("Grande");
                }
            }
        }
        
        txtComplexion.setEditable(false);        
    }//GEN-LAST:event_txtComplexionActionPerformed

    private void cbFemeninoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFemeninoMouseClicked
        cbMasculino.setSelected(false);
        cbFemenino.setSelected(true);
    }//GEN-LAST:event_cbFemeninoMouseClicked

    private void cbMasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMasculinoMouseClicked
        cbFemenino.setSelected(false);
        cbMasculino.setSelected(true);
    }//GEN-LAST:event_cbMasculinoMouseClicked

    private void btnExportarWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarWordActionPerformed
        // Generar la exportación de los datos
        Paciente paciente = new Paciente();
        paciente.setAbdomen(txtAbdomen.getText());
        paciente.setAbdominal(txtAbdominal.getText());
        paciente.setActividadFisica(cmbActividadFisica.getModel().getSelectedItem().toString());
        paciente.setAxilar(txtAxilar.getText());
        paciente.setBiceps(txtBiceps.getText());
        paciente.setBrazoContraido(txtBrazoContraido.getText());
        paciente.setBrazoRelajado(txtBrazoRelajado.getText());
        paciente.setCadera(txtCadera.getText());
        paciente.setCc(txtCC.getText());
        paciente.setCintura(txtCintura.getText());
        paciente.setClasificacion(txtClasificacion.getText());
        paciente.setComplexion(txtComplexion.getText());
        paciente.setCrestaIliaca(txtCrestaIliaca.getText());
        paciente.setEctomorfia(txtEctomorfia.getText());
        paciente.setEctomorfiaRCD(txtEctomorfiaRCD.getText());
        paciente.setEdad(txtEdad.getText());
        paciente.setEndomorfia(txtEndomorfia.getText());
        paciente.setEndomorfiaRCD(txtEndomorfiaRCD.getText());
        paciente.setEstatura(txtEstatura.getText());
        paciente.setEstiloideo(txtEstiloideo.getText());
        paciente.setFemur(txtFemur.getText());
        paciente.setHumero(txtHumero.getText());
        paciente.setIcc(txtICC.getText());
        paciente.setImc(txtIMC.getText());
        paciente.setKgGrasa(txtKgGrasa.getText());
        paciente.setKgMusculo(txtKgMusculo.getText());
        paciente.setKgOseo(txtKgOseo.getText());
        paciente.setKgResidual(txtKgResidual.getText());
        paciente.setMasaMagra(txtMasaMagra.getText());
        paciente.setMesomorfia(txtMesomorfia.getText());
        paciente.setMesomorfiaRCD(txtMesomorfiaRCD.getText());
        paciente.setMusloFrontal(txtMusloFrontal.getText());
        paciente.setNombre(txtNombre.getText());
        paciente.setPantorrilla(txtPantorrilla.getText());
        paciente.setPantorrillaMedial(txtPantorrillaMedial.getText());
        paciente.setPectoral(txtPectoral.getText());
        paciente.setPeso(txtPeso.getText());
        paciente.setPorcentajeGrasaRCD(txtPorcentajeGrasaRCD.getText());
        paciente.setPorcentajeGrasaReal(txtPorcentajeGrasaReal.getText());
        paciente.setPorcentajeMusculoRCD(txtPorcentajeMusculoRCD.getText());
        paciente.setPorcentajeMusculoReal(txtPorcentajeMusculoReal.getText());
        paciente.setPorcentajeOseoRCD(txtPorcentajeOseoRCD.getText());
        paciente.setPorcentajeOseoReal(txtPorcentajeOseoReal.getText());
        paciente.setPorcentajeResidualRCD(txtPorcentajeResidualRCD.getText());
        paciente.setPorcentajeResidualReal(txtPorcentajeResidualReal.getText());
        paciente.setSexo(cbMasculino.isSelected());
        paciente.setSubescapular(txtSubescapular.getText());
        paciente.setSupraespinal(txtSupraespinal.getText());
        paciente.setTriceps(txtTriceps.getText());
        
        try {
            if(!txtEctomorfiaRCD.getText().isEmpty() || !txtEndomorfiaRCD.getText().isEmpty() || !txtMesomorfiaRCD.getText().isEmpty()){
                ExportToWord.exportation(paciente);
                JOptionPane.showMessageDialog(rootPane, "Exportación a Word completada, presione Aceptar para ver su archivo");
                Process p = Runtime.getRuntime().exec("explorer.exe " + paciente.getNombre());
                p.waitFor();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Necesita introducir los datos de somatotipo recomendados antes de exportar a Word");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la exportación: " + ex.getMessage());
            Logger.getLogger(Laboratorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnExportarWordActionPerformed

    private void txtTricepsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTricepsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtSubescapular.requestFocus();
        }
    }//GEN-LAST:event_txtTricepsKeyReleased

    private void txtSubescapularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubescapularKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtBiceps.requestFocus();
        }
    }//GEN-LAST:event_txtSubescapularKeyReleased

    private void txtEdadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtPeso.requestFocus();
        }
    }//GEN-LAST:event_txtEdadKeyReleased

    private void txtPesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtEstatura.requestFocus();
        }
    }//GEN-LAST:event_txtPesoKeyReleased

    private void txtBicepsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBicepsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtPectoral.requestFocus();
        }
    }//GEN-LAST:event_txtBicepsKeyReleased

    private void txtPectoralKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPectoralKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtAxilar.requestFocus();
        }
    }//GEN-LAST:event_txtPectoralKeyReleased

    private void txtAxilarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAxilarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtCrestaIliaca.requestFocus();
        }
    }//GEN-LAST:event_txtAxilarKeyReleased

    private void txtCrestaIliacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCrestaIliacaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtSupraespinal.requestFocus();
        }
    }//GEN-LAST:event_txtCrestaIliacaKeyReleased

    private void txtSupraespinalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupraespinalKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtAbdominal.requestFocus();
        }
    }//GEN-LAST:event_txtSupraespinalKeyReleased

    private void txtAbdominalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbdominalKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtMusloFrontal.requestFocus();
        }
    }//GEN-LAST:event_txtAbdominalKeyReleased

    private void txtMusloFrontalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMusloFrontalKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtPantorrillaMedial.requestFocus();
        }
    }//GEN-LAST:event_txtMusloFrontalKeyReleased

    private void txtPantorrillaMedialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPantorrillaMedialKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtBrazoRelajado.requestFocus();
        }
    }//GEN-LAST:event_txtPantorrillaMedialKeyReleased

    private void txtBrazoRelajadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrazoRelajadoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtBrazoContraido.requestFocus();
        }
    }//GEN-LAST:event_txtBrazoRelajadoKeyReleased

    private void txtBrazoContraidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrazoContraidoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtCintura.requestFocus();
        }
    }//GEN-LAST:event_txtBrazoContraidoKeyReleased

    private void txtCinturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCinturaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtAbdomen.requestFocus();
        }
    }//GEN-LAST:event_txtCinturaKeyReleased

    private void txtAbdomenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbdomenKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtCadera.requestFocus();
        }
    }//GEN-LAST:event_txtAbdomenKeyReleased

    private void txtCaderaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCaderaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtPantorrilla.requestFocus();
        }
    }//GEN-LAST:event_txtCaderaKeyReleased

    private void txtPantorrillaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPantorrillaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtHumero.requestFocus();
        }
    }//GEN-LAST:event_txtPantorrillaKeyReleased

    private void txtHumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHumeroKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtEstiloideo.requestFocus();
        }
    }//GEN-LAST:event_txtHumeroKeyReleased

    private void txtEstiloideoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstiloideoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Pasar a otro textfield
            txtFemur.requestFocus();
        }
    }//GEN-LAST:event_txtEstiloideoKeyReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratorio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDurninWomersley;
    private javax.swing.JButton btnExportarWord;
    private javax.swing.JToggleButton btnJacksonAndPollock;
    private javax.swing.JToggleButton btnJacksonPollock;
    private javax.swing.JToggleButton btnKatchMcArdle;
    private javax.swing.JToggleButton btnLewisHaskell;
    private javax.swing.JToggleButton btnPolloclkLaughridge;
    private javax.swing.JToggleButton btnSloan;
    private javax.swing.JToggleButton btnSloanBurtBlyth;
    private javax.swing.JToggleButton btnThorlandJohnson;
    private javax.swing.JToggleButton btnWilmoreBehnke;
    private javax.swing.JToggleButton btnWithersCraig;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbFemenino;
    private javax.swing.JCheckBox cbMasculino;
    private javax.swing.JComboBox cmbActividadFisica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelComposicionCorporal;
    private javax.swing.JPanel panelDatosPersonales;
    private javax.swing.JPanel panelMediciones;
    private javax.swing.JTabbedPane tpDatosPersonales;
    private javax.swing.JTextField txtAbdomen;
    private javax.swing.JTextField txtAbdominal;
    private javax.swing.JTextField txtAxilar;
    private javax.swing.JTextField txtBiceps;
    private javax.swing.JTextField txtBrazoContraido;
    private javax.swing.JTextField txtBrazoRelajado;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtCadera;
    private javax.swing.JTextField txtCintura;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtComplexion;
    private javax.swing.JTextField txtCrestaIliaca;
    private javax.swing.JTextField txtEctomorfia;
    private javax.swing.JTextField txtEctomorfiaRCD;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEndomorfia;
    private javax.swing.JTextField txtEndomorfiaRCD;
    private javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtEstiloideo;
    private javax.swing.JTextField txtFemur;
    private javax.swing.JTextField txtHumero;
    private javax.swing.JTextField txtICC;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtKgGrasa;
    private javax.swing.JTextField txtKgMusculo;
    private javax.swing.JTextField txtKgOseo;
    private javax.swing.JTextField txtKgResidual;
    private javax.swing.JTextField txtMasaMagra;
    private javax.swing.JTextField txtMesomorfia;
    private javax.swing.JTextField txtMesomorfiaRCD;
    private javax.swing.JTextField txtMusloFrontal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPantorrilla;
    private javax.swing.JTextField txtPantorrillaMedial;
    private javax.swing.JTextField txtPectoral;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPorcentajeGrasaRCD;
    private javax.swing.JTextField txtPorcentajeGrasaReal;
    private javax.swing.JTextField txtPorcentajeMusculoRCD;
    private javax.swing.JTextField txtPorcentajeMusculoReal;
    private javax.swing.JTextField txtPorcentajeOseoRCD;
    private javax.swing.JTextField txtPorcentajeOseoReal;
    private javax.swing.JTextField txtPorcentajeResidualRCD;
    private javax.swing.JTextField txtPorcentajeResidualReal;
    private javax.swing.JTextField txtSubescapular;
    private javax.swing.JTextField txtSupraespinal;
    private javax.swing.JTextField txtTriceps;
    // End of variables declaration//GEN-END:variables
}
