/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package index;

/**
 *
 * @author delamora
 */
public class MedidasVideos extends javax.swing.JFrame {

    /**
     * Creates new form Glosario
     */
    public MedidasVideos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadera = new javax.swing.JButton();
        btnBrazo = new javax.swing.JButton();
        btnCircunferenciaPantorrilla = new javax.swing.JButton();
        btnAbdomen = new javax.swing.JButton();
        btnBrazoContraido = new javax.swing.JButton();
        btnCintura = new javax.swing.JButton();
        btnBiestiloideo = new javax.swing.JButton();
        btnFemoral = new javax.swing.JButton();
        btnHumeral = new javax.swing.JButton();
        btnPeso = new javax.swing.JButton();
        btnAbdominal = new javax.swing.JButton();
        btnAxilar = new javax.swing.JButton();
        btnBiceps = new javax.swing.JButton();
        btnCrestaIliaca = new javax.swing.JButton();
        btnPlieguePantorrilla = new javax.swing.JButton();
        btnMusloAnterior = new javax.swing.JButton();
        btnPectoral = new javax.swing.JButton();
        btnSubescapular = new javax.swing.JButton();
        btnSupraespinal = new javax.swing.JButton();
        btnTriciptal = new javax.swing.JButton();
        btnEstatura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(490, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCadera.setText("Circunferencia de cadera");
        btnCadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaderaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 187, -1));

        btnBrazo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBrazo.setText("Circunferencia de brazo");
        btnBrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrazoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 187, -1));

        btnCircunferenciaPantorrilla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCircunferenciaPantorrilla.setText("Circunferencia de pantorrilla");
        btnCircunferenciaPantorrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircunferenciaPantorrillaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCircunferenciaPantorrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        btnAbdomen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAbdomen.setText("Circunferencia de abdomen");
        btnAbdomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbdomenActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbdomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 187, -1));

        btnBrazoContraido.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnBrazoContraido.setText("Circunferencia brazo contraido");
        btnBrazoContraido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrazoContraidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrazoContraido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 187, -1));

        btnCintura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCintura.setText("Circunferencia de cintura");
        btnCintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 187, -1));

        btnBiestiloideo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBiestiloideo.setText("Diámetro biestiloideo");
        btnBiestiloideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiestiloideoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBiestiloideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 187, -1));

        btnFemoral.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFemoral.setText("Diámetro femoral");
        btnFemoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemoralActionPerformed(evt);
            }
        });
        getContentPane().add(btnFemoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 187, -1));

        btnHumeral.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnHumeral.setText("Diámetro humeral");
        btnHumeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHumeralActionPerformed(evt);
            }
        });
        getContentPane().add(btnHumeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 187, -1));

        btnPeso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPeso.setText("Peso");
        btnPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 187, -1));

        btnAbdominal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAbdominal.setText("Pliegue abdominal");
        btnAbdominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbdominalActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbdominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 187, -1));

        btnAxilar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAxilar.setText("Pliegue axilar");
        btnAxilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAxilarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAxilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 187, -1));

        btnBiceps.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBiceps.setText("Pliegue biceps");
        btnBiceps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBicepsActionPerformed(evt);
            }
        });
        getContentPane().add(btnBiceps, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 187, -1));

        btnCrestaIliaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCrestaIliaca.setText("Pliegue cresta ilíaca");
        btnCrestaIliaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrestaIliacaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrestaIliaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 187, -1));

        btnPlieguePantorrilla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPlieguePantorrilla.setText("Pliegue pantorrilla");
        btnPlieguePantorrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlieguePantorrillaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlieguePantorrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 187, -1));

        btnMusloAnterior.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnMusloAnterior.setText("Pliegue muslo anterior");
        btnMusloAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusloAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnMusloAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 187, -1));

        btnPectoral.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPectoral.setText("Pliegue pectoral");
        btnPectoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPectoralActionPerformed(evt);
            }
        });
        getContentPane().add(btnPectoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 187, -1));

        btnSubescapular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSubescapular.setText("Pliegue subescapular");
        btnSubescapular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubescapularActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubescapular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 187, -1));

        btnSupraespinal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSupraespinal.setText("Pliegue supraespinal");
        btnSupraespinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupraespinalActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupraespinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 187, -1));

        btnTriciptal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTriciptal.setText("Pliegue triciptal");
        btnTriciptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriciptalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTriciptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 187, -1));

        btnEstatura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEstatura.setText("Estatura");
        btnEstatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstaturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 187, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Como tomar las medidas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo3 5x6.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaderaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Circunferencia cadera.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnCaderaActionPerformed

    private void btnBrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrazoActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Circunferencia de brazo.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnBrazoActionPerformed

    private void btnCircunferenciaPantorrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircunferenciaPantorrillaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Circunferencia de pantorrilla.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnCircunferenciaPantorrillaActionPerformed

    private void btnAbdomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbdomenActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Cirfunferencia de abdomen.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnAbdomenActionPerformed

    private void btnBrazoContraidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrazoContraidoActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\cirfunferencia de brazo contraido.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnBrazoContraidoActionPerformed

    private void btnCinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinturaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\cirunferencia de cintura.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnCinturaActionPerformed
	
	private void btnBiestiloideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiestiloideoActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Diametro biestiloideo.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnBiestiloideoActionPerformed

    private void btnFemoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemoralActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Diametro femoral.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnFemoralActionPerformed

    private void btnHumeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHumeralActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Diametro humeral.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnHumeralActionPerformed

    private void btnPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesoActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Peso.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnPesoActionPerformed

    private void btnEstaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstaturaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Estatura.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnEstaturaActionPerformed

    private void btnTriciptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriciptalActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue tricipital.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnTriciptalActionPerformed

    private void btnSupraespinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupraespinalActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue supraespinal.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnSupraespinalActionPerformed

    private void btnSubescapularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubescapularActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue subescapular.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnSubescapularActionPerformed

    private void btnPectoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPectoralActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue pectoral.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnPectoralActionPerformed

    private void btnMusloAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusloAnteriorActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue muslo anterior.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnMusloAnteriorActionPerformed

    private void btnPlieguePantorrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlieguePantorrillaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue de pantorrilla.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnPlieguePantorrillaActionPerformed

    private void btnCrestaIliacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrestaIliacaActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue cresta iliaca.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnCrestaIliacaActionPerformed

    private void btnBicepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBicepsActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue biceps.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnBicepsActionPerformed

    private void btnAxilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAxilarActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue axilar.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnAxilarActionPerformed

    private void btnAbdominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbdominalActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "resources\\videos\\Pliegue abdominal.mp4");
        } catch (Exception e){}
    }//GEN-LAST:event_btnAbdominalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedidasVideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedidasVideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedidasVideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedidasVideos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedidasVideos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbdomen;
    private javax.swing.JButton btnAbdominal;
    private javax.swing.JButton btnAxilar;
    private javax.swing.JButton btnBiceps;
    private javax.swing.JButton btnBiestiloideo;
    private javax.swing.JButton btnBrazo;
    private javax.swing.JButton btnBrazoContraido;
    private javax.swing.JButton btnCadera;
    private javax.swing.JButton btnCintura;
    private javax.swing.JButton btnCircunferenciaPantorrilla;
    private javax.swing.JButton btnCrestaIliaca;
    private javax.swing.JButton btnEstatura;
    private javax.swing.JButton btnFemoral;
    private javax.swing.JButton btnHumeral;
    private javax.swing.JButton btnMusloAnterior;
    private javax.swing.JButton btnPectoral;
    private javax.swing.JButton btnPeso;
    private javax.swing.JButton btnPlieguePantorrilla;
    private javax.swing.JButton btnSubescapular;
    private javax.swing.JButton btnSupraespinal;
    private javax.swing.JButton btnTriciptal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
